### ISSUE TITLE
双流join问题

### ISSUE THREAD

**Issue by makunsusu** [apache/rocketmq-streams#103]
1，JoinTest中的双流测试用例的文件是你们开发者本机的路径，我自己造了两个文件去做join，无法输出join后的结果
2，如果left Source和right Source都是from rocket mq，会有异常

**Comment by duhenglucky** [comment]
@makunsusu 我测试一下

**Comment by duhenglucky** [comment]
@makunsusu 是不是过滤条件写反了，可以加钉钉群，我们一起看看：33053041
