### ISSUE TITLE
There is no log output when rocketmq-streams running. 

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#149]
There is no rocketmq-streams log output right now, when a APP running base on rocketmq-streams. It is inconvenient for troubleshooting.
We can implement a inner log, which should not conflict with user's local log dependencies. A client log in rocketmq:
[org.apache.rocketmq.client.log.ClientLogger](https://github.com/apache/rocketmq/blob/develop/client/src/main/java/org/apache/rocketmq/client/log/ClientLogger.java)

which solve this problem based on **[InnerLoggerFactory](https://github.com/apache/rocketmq/blob/develop/logging/src/main/java/org/apache/rocketmq/logging/InnerLoggerFactory.java)** .

There are other log dependency, such as log4j, in rocketmq-streams, we also need remove it and only use one log dependency.

**Comment by selectbook** [comment]
Hello, I would like to contribute in this issue. can i have a try?

**Comment by ni-ze** [comment]
> Hello, I would like to contribute in this issue. can i have a try?
of course, welcome!
