### ISSUE TITLE
Implement of Apache RocketMQ Streams dispatching system

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq-streams#159]
题目名称：Apache RocketMQ Streams 调度系统的实现
导师介绍：程君杰, Apache RocketMQ Committer
导师邮箱：jet.j.j.cheng@gmail.com
题目难度：进阶
题目描述：通过调度系统， 实时任务实例可以在Rocketmq Streams集群中实现动态的调度；
相关材料：
RocketMQ Streams 代码 / 文档
https://github.com/apache/rocketmq-streams
https://jet-cheng.gitbook.io/rocketmq-streams

1、学习Apache Rocketmq Streams的知识， 学习了解Rocketmq Streams的场景、使用方式、参数意义等；
2、了解Rocketmq Streams实例以及任务之间的关系，实现轻量化的任务调度功能，实现任务的差异化运行；
3、在社区中提交Issue，完成相关代码，review后被社区合并

**Comment by hzh0425** [comment]
Hi, I am very interested in this project, how should I know more about the requirements of this project?

**Comment by ShannonDing** [comment]
> Hi, I am very interested in this project, how should I know more about the requirements of this project? @ShannonDing By the way, how should I contact the mentor of this project?

Hi, I add the contact of the mentor to the issue comment.
