### ISSUE TITLE
support custom function

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#213]

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Has PR**

This issue requests support for custom functions in RocketMQ Streams. A fix has already been submitted in PR #212 (`[ISSUE #213]fix(custom function) support utf`).

Please review and merge the associated PR if it meets the requirements.

---
*Automated evaluation by @RockteMQ-AI*

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Has PR**

This issue requests support for custom functions in RocketMQ Streams. A fix has already been submitted in PR #212.

Please review and merge the associated PR if it meets the requirements.

---
*Automated evaluation by @RockteMQ-AI*
