### ISSUE TITLE
Duplicate Unit Test

### ISSUE THREAD

**Issue by selectbook** [apache/rocketmq-streams#214]
Under the test of the rocketmq-streams-configurable module, there are duplicate packages configuable and duplicate unit test classes ConfigurableComponentTest

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Has PR**

This issue reports duplicate packages (`configuable`) and duplicate unit test classes (`ConfigurableComponentTest`) in the `rocketmq-streams-configurable` module. A fix has already been submitted in PR #215.

Please review and merge the associated PR if it resolves the duplication.

---
*Automated evaluation by @RockteMQ-AI*
