### ISSUE TITLE
Finish data processing when function return null.

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#246]
In map and flatmap function, no data will be produced in some scenes, so there is no necessary pass it to next function.

**Comment by Jargon9** [comment]
Please assign it to me.

**Comment by joeCarf** [comment]
I'd like to do this. plz assign it to me

**Comment by elenacliu** [comment]
Can you provide more detail? For example, I'm wondering whether I should close the whole stream or just not pass the data to the next function and directly output to the sink.

**Comment by elenacliu** [comment]
hi, I'm doing this these days, plz assign it to me.

**Comment by elenacliu** [comment]
After more insight into the project, I think I should stop forward the data to the next processor node if the data output is `null`

> Can you provide more detail? For example, I'm wondering whether I should close the whole stream or just not pass the data to the next function and directly output to the sink.
