### ISSUE TITLE
Support flatMap function in GroupedStream

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#247]
flatmap function takes one element and produces zero, one, or more elements.  such as, a flatmap function splits sentences to words:

`flatmap("hello world") -> "hello" "world"`

**Comment by selectbook** [comment]
please assign it to me

**Comment by joeCarf** [comment]
I'd like to do this. plz assign it to me

**Comment by elenacliu** [comment]
Can you assign it to me? I‘m working on this these days.
