### ISSUE TITLE
Support avg function in WindowStream 

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#251]

**Comment by Jargon96** [comment]
Hi teams, I want to handle this. Could you please assign it to me ?

**Comment by ni-ze** [comment]
@Jargon9 OK, It already assign to you. Please clone from develop branch, and merge the your pr back into it.
The develop branch is the default branch, I will  change the default branch in the next feature days.

**Comment by Jargon9** [comment]
@ni-ze Got it! thanks very much.

**Comment by Jargon9** [comment]
Hi teams, I have completed the main part of avg calculation. Could you please review the code?
