### ISSUE TITLE
Why does flatMap interface return RStream<T> instead of RStream<VR> ？

### ISSUE THREAD

**Issue by huangql** [apache/rocketmq-streams#268]
<VR> RStream<T> flatMap(final ValueMapperAction<T, ? extends Iterable<? extends VR>> mapper);

Why does this interface return RStream<T> instead of RStream<VR> ？
How do I get RStream<VR> ？
I want to keyBy  with VR.id

**Comment by ni-ze** [comment]
@huangql It does a bug, can you submit a pr to correct it?
