### ISSUE TITLE
support subscribe topic from first

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#272]
In current version, subscribe topic from last. In some scenes, we need subscribe topic from first.

**Comment by Jargon9** [comment]
Do you mean consume message from first offset of topic? besides, Could you please assign it to me?

**Comment by ni-ze** [comment]
Yeah, exactly.

**Comment by Jargon9** [comment]
@ni-ze I have fix it, Could you please reopen this pr?
