### ISSUE TITLE
Do not process data coms from removed MessageQueue.

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#281]
![image](https://user-images.githubusercontent.com/31175234/231442446-dc40a87f-9013-4ec2-9bdf-eb6506b41b1d.png)

**Comment by DevPJ9** [comment]
Hello @ni-ze. I would like to work on this.

**Comment by DevPJ9** [comment]
Hello, @ni-ze. Can you please provide a little more details in the requirement?

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Needs Info**

This issue describes a problem where data from a removed MessageQueue is still being processed, which sounds like a correctness issue in the consumer/assignment logic.

However, the issue currently only contains an image without a text description. To properly investigate and verify this against the codebase, please provide:
- [ ] A text description of the expected vs actual behavior
- [ ] Steps to reproduce the issue
- [ ] RocketMQ Streams version
- [ ] Relevant log output (as text, not screenshot)
- [ ] Which module is affected (e.g., consumer assignment, window computation, source splitting)

This will help determine if this is still reproducible in the current codebase.

---
*Automated evaluation by RocketMQ AI Assistant*
