### ISSUE TITLE
Will there be a complete test framework in the future to test the functions?

### ISSUE THREAD

**Issue by elenacliu** [apache/rocketmq-streams#285]

**Comment by ni-ze** [comment]
It should have. However, I have no time to do this, so it is not has a complete unit tests for now. 
Are you interested in participating in unit testing contributions?

**Comment by elenacliu** [comment]
Yes I'm interested in that, but I have little idea about how to setup a complete test framework in java now. Maybe you can provide a foundamental framework in the future and I can add unit tests to it.
