### ISSUE TITLE
The logic of watermark judging whether to solve the data may result in missing data.

### ISSUE THREAD

**Issue by starmilkxin** [apache/rocketmq-streams#290]
![image](https://github.com/apache/rocketmq-streams/assets/55646681/e5845435-17b5-4429-b35b-65699d93e7cc)

```java
  long time = this.context.getDataTime();

  long watermark = this.watermark(time - allowDelay, stateTopicMessageQueue);
  if (time < watermark) {
      //已经触发，丢弃数据
      logger.warn("discard data:[{}], window has been fired. time of data:{}, watermark:{}",
              data, time, watermark);
      return;
  }
```

It is expected that the dataA should be included in the time window, but the current logic is to discard it directly.

Should it be based on the end time of the time window?

**Comment by ni-ze** [comment]
The watermark is based on the endTime of window:
![image](https://github.com/apache/rocketmq-streams/assets/31175234/a8d03f5b-a1ee-4125-97a8-bc040aaf4ae4)

But I agree, commit(store) watermark into RocksDB should only happened after window fired.

store watermark when data coming is not correct.
![image](https://github.com/apache/rocketmq-streams/assets/31175234/900619f8-1d85-4626-b23e-1b74b9e55b84)

**Comment by ni-ze** [comment]
can you submit a pr to solve this? thx.
