### ISSUE TITLE
what's the difference between `AccumulatorSupplier.java` and `AggregateSupplier.java`?

### ISSUE THREAD

**Issue by elenacliu** [apache/rocketmq-streams#298]
I'm wondering the difference between `AccumulatorSupplier.java` and `AggregateSupplier.java`, because it seems that `AggregateSupplier.java` can do what `AccumulatorSupplier.java` do.

**Comment by ni-ze** [comment]
The different is the param of construction:
Accumulator separate the adding data from getting the aggregate result. It has two phase.
