### ISSUE TITLE
Add 2 user examples using different `window` type and `keyBy` by more than one keys

### ISSUE THREAD

**Issue by elenacliu** [apache/rocketmq-streams#304]

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `type/enhancement` | Status: **Evaluated**

Adding user examples with different window types (e.g., tumbling, sliding, session windows) is a good enhancement for documentation and developer onboarding.

**Feasibility:** Straightforward — add example classes demonstrating each window type.
**Scope:** Examples module.
**Compatibility:** Additive, no breaking changes.

---
*Automated evaluation by github-manager*
