### ISSUE TITLE
polish example

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#308]

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `question` | Status: **Needs Info**

This issue has no description or details about what needs to be polished. To help evaluate and address this, please provide:

- [ ] Which example(s) need improvement
- [ ] What specific issues exist (outdated code, missing documentation, incorrect behavior, etc.)
- [ ] Expected improvements or changes

Without more context, this issue cannot be triaged or acted upon.

---
*Automated evaluation by RockteMQ-AI*
